a = int(input("Enter value for a : "))
b = int(input("Enter value for b : "))
c = int(input("Enter value for c : "))
d = (b**2) - (4*a*c)
sol1 = (-b+(d**0.5))/(2*a)
sol2 = (-b-(d**0.5))/(2*a)
print('The solution are',sol1,'and',sol2)
